// Code generated by Fern. DO NOT EDIT.

package readtokens

import (
	context "context"

	packagecloud "github.com/cstrahan/packagecloud-go/sdk"
	core "github.com/cstrahan/packagecloud-go/sdk/core"
	internal "github.com/cstrahan/packagecloud-go/sdk/internal"
	option "github.com/cstrahan/packagecloud-go/sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// List read tokens for a master token.
//
// **Example request:**
//
// ```
// curl https://packagecloud.io/api/v1/repos/username/reponame/master_tokens/123/read_tokens.json
// ```
func (c *Client) Index(
	ctx context.Context,
	request *packagecloud.ReadTokensIndexRequest,
	opts ...option.RequestOption,
) (*packagecloud.ReadTokensIndexResponse, error) {
	response, err := c.WithRawResponse.Index(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a read token.
//
// **Example request:**
//
// ```
// curl -X POST -F "read_token[name]=tokename" https://packagecloud.io/api/v1/repos/username/reponame/master_tokens/123/read_tokens.json
// ```
func (c *Client) Create(
	ctx context.Context,
	request *packagecloud.ReadTokensCreateRequest,
	opts ...option.RequestOption,
) (*packagecloud.ReadToken, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// View a single read token
//
// **Example request:**
//
// ```
// curl -X GET https://packagecloud.io/api/v1/repos/username/reponame/master_tokens/123/read_tokens/33
// ```
func (c *Client) Show(
	ctx context.Context,
	request *packagecloud.ReadTokensShowRequest,
	opts ...option.RequestOption,
) (*packagecloud.ReadToken, error) {
	response, err := c.WithRawResponse.Show(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Destroy a read token
//
// **Example request:**
//
// ```
// curl -X DELETE https://packagecloud.io/api/v1/repos/username/reponame/master_tokens/123/read_tokens/33
// ```
func (c *Client) Destroy(
	ctx context.Context,
	request *packagecloud.ReadTokensDestroyRequest,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.Destroy(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
