// Code generated by Fern. DO NOT EDIT.

package stats_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	packagecloud "github.com/cstrahan/packagecloud-go/sdk"
	client "github.com/cstrahan/packagecloud-go/sdk/client"
	option "github.com/cstrahan/packagecloud-go/sdk/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestStatsDownloadsCountDebianRedhatWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsDownloadsCountDebianRedhatRequest{
		UserID:         "user_id",
		Repo:           "repo",
		Type:           "type",
		Distro:         "distro",
		Version:        "version",
		Package:        "package",
		Arch:           "arch",
		PackageVersion: "package_version",
		Release:        "release",
	}
	_, invocationErr := client.Stats.DownloadsCountDebianRedhat(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsDownloadsCountDebianRedhatWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsDownloadsCountDebianRedhatWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/type/distro/version/package/arch/package_version/release/stats/downloads/count.json", nil, 1)
}

func TestStatsDownloadsCountGemWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsDownloadsCountGemRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Package: "package",
		Version: "version",
	}
	_, invocationErr := client.Stats.DownloadsCountGem(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsDownloadsCountGemWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsDownloadsCountGemWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/gem/package/version/stats/downloads/count.json", nil, 1)
}

func TestStatsDownloadsCountPythonWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsDownloadsCountPythonRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Package: "package",
		Version: "version",
	}
	_, invocationErr := client.Stats.DownloadsCountPython(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsDownloadsCountPythonWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsDownloadsCountPythonWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/python/package/version/stats/downloads/count.json", nil, 1)
}

func TestStatsDownloadsCountNodeJsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsDownloadsCountNodeJsRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Package: "package",
		Version: "version",
	}
	_, invocationErr := client.Stats.DownloadsCountNodeJs(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsDownloadsCountNodeJsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsDownloadsCountNodeJsWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/node/package/version/stats/downloads/count.json", nil, 1)
}

func TestStatsDownloadsDetailDebianRedhatWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsDownloadsDetailDebianRedhatRequest{
		UserID:         "user_id",
		Repo:           "repo",
		Type:           "type",
		Distro:         "distro",
		Version:        "version",
		Package:        "package",
		Arch:           "arch",
		PackageVersion: "package_version",
		Release:        "release",
	}
	_, invocationErr := client.Stats.DownloadsDetailDebianRedhat(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsDownloadsDetailDebianRedhatWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsDownloadsDetailDebianRedhatWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/type/distro/version/package/arch/package_version/release/stats/downloads/detail.json", nil, 1)
}

func TestStatsDownloadsDetailGemWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsDownloadsDetailGemRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Package: "package",
		Version: "version",
	}
	_, invocationErr := client.Stats.DownloadsDetailGem(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsDownloadsDetailGemWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsDownloadsDetailGemWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/gem/package/version/stats/downloads/detail.json", nil, 1)
}

func TestStatsDownloadsDetailPythonWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsDownloadsDetailPythonRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Package: "package",
		Version: "version",
	}
	_, invocationErr := client.Stats.DownloadsDetailPython(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsDownloadsDetailPythonWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsDownloadsDetailPythonWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/python/package/version/stats/downloads/detail.json", nil, 1)
}

func TestStatsDownloadsDetailNodeJsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsDownloadsDetailNodeJsRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Package: "package",
		Version: "version",
	}
	_, invocationErr := client.Stats.DownloadsDetailNodeJs(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsDownloadsDetailNodeJsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsDownloadsDetailNodeJsWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/node/package/version/stats/downloads/detail.json", nil, 1)
}

func TestStatsDownloadsSeriesDebianRedhatWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsDownloadsSeriesDebianRedhatRequest{
		UserID:         "user_id",
		Repo:           "repo",
		Type:           "type",
		Distro:         "distro",
		Version:        "version",
		Package:        "package",
		Arch:           "arch",
		PackageVersion: "package_version",
		Release:        "release",
		Interval:       "interval",
	}
	_, invocationErr := client.Stats.DownloadsSeriesDebianRedhat(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsDownloadsSeriesDebianRedhatWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsDownloadsSeriesDebianRedhatWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/type/distro/version/package/arch/package_version/release/stats/downloads/series/interval.json", nil, 1)
}

func TestStatsDownloadsSeriesGemWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsDownloadsSeriesGemRequest{
		UserID:   "user_id",
		Repo:     "repo",
		Package:  "package",
		Version:  "version",
		Interval: "interval",
	}
	_, invocationErr := client.Stats.DownloadsSeriesGem(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsDownloadsSeriesGemWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsDownloadsSeriesGemWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/gem/package/version/stats/downloads/series/interval.json", nil, 1)
}

func TestStatsDownloadsSeriesPythonWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsDownloadsSeriesPythonRequest{
		UserID:   "user_id",
		Repo:     "repo",
		Package:  "package",
		Version:  "version",
		Interval: "interval",
	}
	_, invocationErr := client.Stats.DownloadsSeriesPython(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsDownloadsSeriesPythonWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsDownloadsSeriesPythonWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/python/package/version/stats/downloads/series/interval.json", nil, 1)
}

func TestStatsDownloadsSeriesNodeJsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsDownloadsSeriesNodeJsRequest{
		UserID:   "user_id",
		Repo:     "repo",
		Package:  "package",
		Version:  "version",
		Interval: "interval",
	}
	_, invocationErr := client.Stats.DownloadsSeriesNodeJs(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsDownloadsSeriesNodeJsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsDownloadsSeriesNodeJsWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/node/package/version/stats/downloads/series/interval.json", nil, 1)
}

func TestStatsInstallsCountAllWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsInstallsCountAllRequest{
		UserID: "user_id",
		Repo:   "repo",
	}
	_, invocationErr := client.Stats.InstallsCountAll(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsInstallsCountAllWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsInstallsCountAllWithWireMock", "GET", "/api/v1/repos/user_id/repo/stats/installs/count.json", nil, 1)
}

func TestStatsInstallsCountByDistroWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsInstallsCountByDistroRequest{
		UserID: "user_id",
		Repo:   "repo",
		Distro: "distro",
	}
	_, invocationErr := client.Stats.InstallsCountByDistro(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsInstallsCountByDistroWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsInstallsCountByDistroWithWireMock", "GET", "/api/v1/repos/user_id/repo/stats/installs/distro/count.json", nil, 1)
}

func TestStatsInstallsCountByDistroAndVersionWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsInstallsCountByDistroAndVersionRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Distro:  "distro",
		Version: "version",
	}
	_, invocationErr := client.Stats.InstallsCountByDistroAndVersion(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsInstallsCountByDistroAndVersionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsInstallsCountByDistroAndVersionWithWireMock", "GET", "/api/v1/repos/user_id/repo/stats/installs/distro/version/count.json", nil, 1)
}

func TestStatsInstallsDetailAllWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsInstallsDetailAllRequest{
		UserID: "user_id",
		Repo:   "repo",
	}
	_, invocationErr := client.Stats.InstallsDetailAll(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsInstallsDetailAllWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsInstallsDetailAllWithWireMock", "GET", "/api/v1/repos/user_id/repo/stats/installs/detail.json", nil, 1)
}

func TestStatsInstallsDetailByDistroWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsInstallsDetailByDistroRequest{
		UserID: "user_id",
		Repo:   "repo",
		Distro: "distro",
	}
	_, invocationErr := client.Stats.InstallsDetailByDistro(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsInstallsDetailByDistroWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsInstallsDetailByDistroWithWireMock", "GET", "/api/v1/repos/user_id/repo/stats/installs/distro/detail.json", nil, 1)
}

func TestStatsInstallsDetailByDistroAndVersionWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsInstallsDetailByDistroAndVersionRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Distro:  "distro",
		Version: "version",
	}
	_, invocationErr := client.Stats.InstallsDetailByDistroAndVersion(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsInstallsDetailByDistroAndVersionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsInstallsDetailByDistroAndVersionWithWireMock", "GET", "/api/v1/repos/user_id/repo/stats/installs/distro/version/detail.json", nil, 1)
}

func TestStatsInstallsSeriesAllWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsInstallsSeriesAllRequest{
		UserID:   "user_id",
		Repo:     "repo",
		Interval: "interval",
	}
	_, invocationErr := client.Stats.InstallsSeriesAll(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsInstallsSeriesAllWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsInstallsSeriesAllWithWireMock", "GET", "/api/v1/repos/user_id/repo/stats/installs/series/interval.json", nil, 1)
}

func TestStatsInstallsSeriesByDistroWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsInstallsSeriesByDistroRequest{
		UserID:   "user_id",
		Repo:     "repo",
		Distro:   "distro",
		Interval: "interval",
	}
	_, invocationErr := client.Stats.InstallsSeriesByDistro(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsInstallsSeriesByDistroWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsInstallsSeriesByDistroWithWireMock", "GET", "/api/v1/repos/user_id/repo/stats/installs/distro/series/interval.json", nil, 1)
}

func TestStatsInstallsSeriesByDistroAndVersionWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.StatsInstallsSeriesByDistroAndVersionRequest{
		UserID:   "user_id",
		Repo:     "repo",
		Distro:   "distro",
		Version:  "version",
		Interval: "interval",
	}
	_, invocationErr := client.Stats.InstallsSeriesByDistroAndVersion(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestStatsInstallsSeriesByDistroAndVersionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestStatsInstallsSeriesByDistroAndVersionWithWireMock", "GET", "/api/v1/repos/user_id/repo/stats/installs/distro/version/series/interval.json", nil, 1)
}
