// Code generated by Fern. DO NOT EDIT.

package gpgkeys

import (
	context "context"

	packagecloud "github.com/cstrahan/packagecloud-go/sdk"
	core "github.com/cstrahan/packagecloud-go/sdk/core"
	internal "github.com/cstrahan/packagecloud-go/sdk/internal"
	option "github.com/cstrahan/packagecloud-go/sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// List gpg keys for a repository.
//
// **Example request:**
//
// ```
// curl https://packagecloud.io/api/v1/repos/username/reponame/gpg_keys.json
// ```
func (c *Client) Index(
	ctx context.Context,
	request *packagecloud.GpgKeysIndexRequest,
	opts ...option.RequestOption,
) (*packagecloud.GpgKeysIndexResponse, error) {
	response, err := c.WithRawResponse.Index(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a GPG key.
//
// **Example request:**
//
// ```
// curl -X POST -F "gpg_key[keydata]=@/path/to/key.gpg" https://packagecloud.io/api/v1/repos/username/reponame/gpg_keys.json
// ```
func (c *Client) Create(
	ctx context.Context,
	request *packagecloud.GpgKeysCreateRequest,
	opts ...option.RequestOption,
) (*packagecloud.GpgKey, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// View a single GPG Key
//
// **Example request:**
//
// ```
// curl -X GET https://packagecloud.io/api/v1/repos/username/reponame/gpg_keys/username-reponame-85D7FBF915DFCBC6.pub.gpg.json
// ```
func (c *Client) Show(
	ctx context.Context,
	request *packagecloud.GpgKeysShowRequest,
	opts ...option.RequestOption,
) (*packagecloud.GpgKey, error) {
	response, err := c.WithRawResponse.Show(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Destroy a GPG key
//
// **Example request:**
//
// ```
// curl -X DELETE https://packagecloud.io/api/v1/repos/username/reponame/gpg_keys/username-reponame-85D7FBF915DFCBC6.pub.gpg.json
// ```
func (c *Client) Destroy(
	ctx context.Context,
	request *packagecloud.GpgKeysDestroyRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Destroy(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
