// Code generated by Fern. DO NOT EDIT.

package gpgkeys

import (
	context "context"
	http "net/http"

	packagecloud "github.com/cstrahan/packagecloud-go/sdk"
	core "github.com/cstrahan/packagecloud-go/sdk/core"
	internal "github.com/cstrahan/packagecloud-go/sdk/internal"
	option "github.com/cstrahan/packagecloud-go/sdk/option"
)

type RawClient struct {
	baseURL string
	caller  *internal.Caller
	options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
	return &RawClient{
		options: options,
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

func (r *RawClient) Index(
	ctx context.Context,
	request *packagecloud.GpgKeysIndexRequest,
	opts ...option.RequestOption,
) (*core.Response[*packagecloud.GpgKeysIndexResponse], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://packagecloud.io",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/repos/%v/%v/gpg_keys.json",
		request.UserID,
		request.Repo,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *packagecloud.GpgKeysIndexResponse
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*packagecloud.GpgKeysIndexResponse]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Create(
	ctx context.Context,
	request *packagecloud.GpgKeysCreateRequest,
	opts ...option.RequestOption,
) (*core.Response[*packagecloud.GpgKey], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://packagecloud.io",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/repos/%v/%v/gpg_keys.json",
		request.UserID,
		request.Repo,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	writer := internal.NewMultipartWriter()
	if request.GpgKeyKeydata != nil {
		if err := writer.WriteFile("gpg_key[keydata]", request.GpgKeyKeydata); err != nil {
			return nil, err
		}
	}
	if err := writer.Close(); err != nil {
		return nil, err
	}
	headers.Set("Content-Type", writer.ContentType())

	var response *packagecloud.GpgKey
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodPost,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Request:         writer.Buffer(),
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*packagecloud.GpgKey]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Show(
	ctx context.Context,
	request *packagecloud.GpgKeysShowRequest,
	opts ...option.RequestOption,
) (*core.Response[*packagecloud.GpgKey], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://packagecloud.io",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/repos/%v/%v/gpg_keys/%v.json",
		request.UserID,
		request.Repo,
		request.Keyname,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response *packagecloud.GpgKey
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodGet,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[*packagecloud.GpgKey]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}

func (r *RawClient) Destroy(
	ctx context.Context,
	request *packagecloud.GpgKeysDestroyRequest,
	opts ...option.RequestOption,
) (*core.Response[map[string]any], error) {
	options := core.NewRequestOptions(opts...)
	baseURL := internal.ResolveBaseURL(
		options.BaseURL,
		r.baseURL,
		"https://packagecloud.io",
	)
	endpointURL := internal.EncodeURL(
		baseURL+"/api/v1/repos/%v/%v/gpg_keys/%v.json",
		request.UserID,
		request.Repo,
		request.Keyname,
	)
	headers := internal.MergeHeaders(
		r.options.ToHeader(),
		options.ToHeader(),
	)
	var response map[string]any
	raw, err := r.caller.Call(
		ctx,
		&internal.CallParams{
			URL:             endpointURL,
			Method:          http.MethodDelete,
			Headers:         headers,
			MaxAttempts:     options.MaxAttempts,
			DisableRetries:  options.DisableRetries,
			BodyProperties:  options.BodyProperties,
			QueryParameters: options.QueryParameters,
			Client:          options.HTTPClient,
			Response:        &response,
		},
	)
	if err != nil {
		return nil, err
	}
	return &core.Response[map[string]any]{
		StatusCode: raw.StatusCode,
		Header:     raw.Header,
		Body:       response,
	}, nil
}
