// Code generated by Fern. DO NOT EDIT.

package stats

import (
	context "context"

	packagecloud "github.com/cstrahan/packagecloud-go/sdk"
	core "github.com/cstrahan/packagecloud-go/sdk/core"
	internal "github.com/cstrahan/packagecloud-go/sdk/internal"
	option "github.com/cstrahan/packagecloud-go/sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Retrieve the number of times a particular package has been downloaded given a
// particular criteria. This is specific to a single package inside a repository.
//
// Default date range is 7 days ago.
//
// Everyone for public repositories, Owners & Collaborators for private repositories.
//
// Instead of constructing these URLs by hand, you should use the generated versions
// returned from any of these API's, which are guaranteed to be correct for all supported package types:
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/package/gem/my-gem/1.2.0/stats/downloads/count.json
// ```
func (c *Client) DownloadsCountDebianRedhat(
	ctx context.Context,
	request *packagecloud.StatsDownloadsCountDebianRedhatRequest,
	opts ...option.RequestOption,
) (*packagecloud.CountValue, error) {
	response, err := c.WithRawResponse.DownloadsCountDebianRedhat(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the number of times a particular package has been downloaded given a
// particular criteria. This is specific to a single package inside a repository.
//
// Default date range is 7 days ago.
//
// Everyone for public repositories, Owners & Collaborators for private repositories.
//
// Instead of constructing these URLs by hand, you should use the generated versions
// returned from any of these API's, which are guaranteed to be correct for all supported package types:
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/package/gem/my-gem/1.2.0/stats/downloads/count.json
// ```
func (c *Client) DownloadsCountGem(
	ctx context.Context,
	request *packagecloud.StatsDownloadsCountGemRequest,
	opts ...option.RequestOption,
) (*packagecloud.CountValue, error) {
	response, err := c.WithRawResponse.DownloadsCountGem(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the number of times a particular package has been downloaded given a
// particular criteria. This is specific to a single package inside a repository.
//
// Default date range is 7 days ago.
//
// Everyone for public repositories, Owners & Collaborators for private repositories.
//
// Instead of constructing these URLs by hand, you should use the generated versions
// returned from any of these API's, which are guaranteed to be correct for all supported package types:
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/package/gem/my-gem/1.2.0/stats/downloads/count.json
// ```
func (c *Client) DownloadsCountPython(
	ctx context.Context,
	request *packagecloud.StatsDownloadsCountPythonRequest,
	opts ...option.RequestOption,
) (*packagecloud.CountValue, error) {
	response, err := c.WithRawResponse.DownloadsCountPython(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the number of times a particular package has been downloaded given a
// particular criteria. This is specific to a single package inside a repository.
//
// Default date range is 7 days ago.
//
// Everyone for public repositories, Owners & Collaborators for private repositories.
//
// Instead of constructing these URLs by hand, you should use the generated versions
// returned from any of these API's, which are guaranteed to be correct for all supported package types:
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/package/gem/my-gem/1.2.0/stats/downloads/count.json
// ```
func (c *Client) DownloadsCountNodeJs(
	ctx context.Context,
	request *packagecloud.StatsDownloadsCountNodeJsRequest,
	opts ...option.RequestOption,
) (*packagecloud.CountValue, error) {
	response, err := c.WithRawResponse.DownloadsCountNodeJs(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the details of all the downloads for a particular package given a
// particular criteria. This is specific to a single package inside a repository.
//
// Default date range is 7 days ago. See response headers for [pagination](#pagination) information.
//
// # Repository owners only
//
// Instead of constructing these URLs by hand, you should use the generated versions
// returned from any of these API's, which are guaranteed to be correct for all supported package types:
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/package/gem/my-gem/1.2.0/stats/downloads/detail.json
// ```
func (c *Client) DownloadsDetailDebianRedhat(
	ctx context.Context,
	request *packagecloud.StatsDownloadsDetailDebianRedhatRequest,
	opts ...option.RequestOption,
) ([]*packagecloud.PackageDownloads, error) {
	response, err := c.WithRawResponse.DownloadsDetailDebianRedhat(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the details of all the downloads for a particular package given a
// particular criteria. This is specific to a single package inside a repository.
//
// Default date range is 7 days ago. See response headers for [pagination](#pagination) information.
//
// # Repository owners only
//
// Instead of constructing these URLs by hand, you should use the generated versions
// returned from any of these API's, which are guaranteed to be correct for all supported package types:
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/package/gem/my-gem/1.2.0/stats/downloads/detail.json
// ```
func (c *Client) DownloadsDetailGem(
	ctx context.Context,
	request *packagecloud.StatsDownloadsDetailGemRequest,
	opts ...option.RequestOption,
) ([]*packagecloud.PackageDownloads, error) {
	response, err := c.WithRawResponse.DownloadsDetailGem(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the details of all the downloads for a particular package given a
// particular criteria. This is specific to a single package inside a repository.
//
// Default date range is 7 days ago. See response headers for [pagination](#pagination) information.
//
// # Repository owners only
//
// Instead of constructing these URLs by hand, you should use the generated versions
// returned from any of these API's, which are guaranteed to be correct for all supported package types:
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/package/gem/my-gem/1.2.0/stats/downloads/detail.json
// ```
func (c *Client) DownloadsDetailPython(
	ctx context.Context,
	request *packagecloud.StatsDownloadsDetailPythonRequest,
	opts ...option.RequestOption,
) ([]*packagecloud.PackageDownloads, error) {
	response, err := c.WithRawResponse.DownloadsDetailPython(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the details of all the downloads for a particular package given a
// particular criteria. This is specific to a single package inside a repository.
//
// Default date range is 7 days ago. See response headers for [pagination](#pagination) information.
//
// # Repository owners only
//
// Instead of constructing these URLs by hand, you should use the generated versions
// returned from any of these API's, which are guaranteed to be correct for all supported package types:
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/package/gem/my-gem/1.2.0/stats/downloads/detail.json
// ```
func (c *Client) DownloadsDetailNodeJs(
	ctx context.Context,
	request *packagecloud.StatsDownloadsDetailNodeJsRequest,
	opts ...option.RequestOption,
) ([]*packagecloud.PackageDownloads, error) {
	response, err := c.WithRawResponse.DownloadsDetailNodeJs(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a time series of all the downloads for a particular package given a
// particular criteria. This is specific to a single package inside a repository.
//
// Default date range is 7 days ago. See response headers for [pagination](#pagination) information.
//
// Everyone for public repositories, Owners & Collaborators for private repositories.
//
// Instead of constructing these URLs by hand, you should use the generated versions
// returned from any of these API's, which are guaranteed to be correct for all supported package types:
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/package/gem/my-gem/1.2.0/stats/downloads/series/daily.json
// ```
func (c *Client) DownloadsSeriesDebianRedhat(
	ctx context.Context,
	request *packagecloud.StatsDownloadsSeriesDebianRedhatRequest,
	opts ...option.RequestOption,
) (*packagecloud.SeriesValue, error) {
	response, err := c.WithRawResponse.DownloadsSeriesDebianRedhat(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a time series of all the downloads for a particular package given a
// particular criteria. This is specific to a single package inside a repository.
//
// Default date range is 7 days ago. See response headers for [pagination](#pagination) information.
//
// Everyone for public repositories, Owners & Collaborators for private repositories.
//
// Instead of constructing these URLs by hand, you should use the generated versions
// returned from any of these API's, which are guaranteed to be correct for all supported package types:
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/package/gem/my-gem/1.2.0/stats/downloads/series/daily.json
// ```
func (c *Client) DownloadsSeriesGem(
	ctx context.Context,
	request *packagecloud.StatsDownloadsSeriesGemRequest,
	opts ...option.RequestOption,
) (*packagecloud.SeriesValue, error) {
	response, err := c.WithRawResponse.DownloadsSeriesGem(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a time series of all the downloads for a particular package given a
// particular criteria. This is specific to a single package inside a repository.
//
// Default date range is 7 days ago. See response headers for [pagination](#pagination) information.
//
// Everyone for public repositories, Owners & Collaborators for private repositories.
//
// Instead of constructing these URLs by hand, you should use the generated versions
// returned from any of these API's, which are guaranteed to be correct for all supported package types:
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/package/gem/my-gem/1.2.0/stats/downloads/series/daily.json
// ```
func (c *Client) DownloadsSeriesPython(
	ctx context.Context,
	request *packagecloud.StatsDownloadsSeriesPythonRequest,
	opts ...option.RequestOption,
) (*packagecloud.SeriesValue, error) {
	response, err := c.WithRawResponse.DownloadsSeriesPython(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a time series of all the downloads for a particular package given a
// particular criteria. This is specific to a single package inside a repository.
//
// Default date range is 7 days ago. See response headers for [pagination](#pagination) information.
//
// Everyone for public repositories, Owners & Collaborators for private repositories.
//
// Instead of constructing these URLs by hand, you should use the generated versions
// returned from any of these API's, which are guaranteed to be correct for all supported package types:
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/package/gem/my-gem/1.2.0/stats/downloads/series/daily.json
// ```
func (c *Client) DownloadsSeriesNodeJs(
	ctx context.Context,
	request *packagecloud.StatsDownloadsSeriesNodeJsRequest,
	opts ...option.RequestOption,
) (*packagecloud.SeriesValue, error) {
	response, err := c.WithRawResponse.DownloadsSeriesNodeJs(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the number of times a particular repository has been installed given a
// particular criteria. This is specific to a single repository.
//
// Default date range is 7 days ago.
//
// Everyone for public repositories, Owners & Collaborators for private repositories.
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/stats/installs/count.json
// ```
func (c *Client) InstallsCountAll(
	ctx context.Context,
	request *packagecloud.StatsInstallsCountAllRequest,
	opts ...option.RequestOption,
) (*packagecloud.CountValue, error) {
	response, err := c.WithRawResponse.InstallsCountAll(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the number of times a particular repository has been installed given a
// particular criteria. This is specific to a single repository.
//
// Default date range is 7 days ago.
//
// Everyone for public repositories, Owners & Collaborators for private repositories.
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/stats/installs/count.json
// ```
func (c *Client) InstallsCountByDistro(
	ctx context.Context,
	request *packagecloud.StatsInstallsCountByDistroRequest,
	opts ...option.RequestOption,
) (*packagecloud.CountValue, error) {
	response, err := c.WithRawResponse.InstallsCountByDistro(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the number of times a particular repository has been installed given a
// particular criteria. This is specific to a single repository.
//
// Default date range is 7 days ago.
//
// Everyone for public repositories, Owners & Collaborators for private repositories.
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/stats/installs/count.json
// ```
func (c *Client) InstallsCountByDistroAndVersion(
	ctx context.Context,
	request *packagecloud.StatsInstallsCountByDistroAndVersionRequest,
	opts ...option.RequestOption,
) (*packagecloud.CountValue, error) {
	response, err := c.WithRawResponse.InstallsCountByDistroAndVersion(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the details of all repository installations that match a
// particular criteria. This is specific to a single repository.
//
// Default date range is 7 days ago. See response headers for [pagination](#pagination) information.
//
// # Repository owners only
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/stats/installs/detail.json
// ```
func (c *Client) InstallsDetailAll(
	ctx context.Context,
	request *packagecloud.StatsInstallsDetailAllRequest,
	opts ...option.RequestOption,
) ([]*packagecloud.RepositoryInstalls, error) {
	response, err := c.WithRawResponse.InstallsDetailAll(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the details of all repository installations that match a
// particular criteria. This is specific to a single repository.
//
// Default date range is 7 days ago. See response headers for [pagination](#pagination) information.
//
// # Repository owners only
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/stats/installs/detail.json
// ```
func (c *Client) InstallsDetailByDistro(
	ctx context.Context,
	request *packagecloud.StatsInstallsDetailByDistroRequest,
	opts ...option.RequestOption,
) ([]*packagecloud.RepositoryInstalls, error) {
	response, err := c.WithRawResponse.InstallsDetailByDistro(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the details of all repository installations that match a
// particular criteria. This is specific to a single repository.
//
// Default date range is 7 days ago. See response headers for [pagination](#pagination) information.
//
// # Repository owners only
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/stats/installs/detail.json
// ```
func (c *Client) InstallsDetailByDistroAndVersion(
	ctx context.Context,
	request *packagecloud.StatsInstallsDetailByDistroAndVersionRequest,
	opts ...option.RequestOption,
) ([]*packagecloud.RepositoryInstalls, error) {
	response, err := c.WithRawResponse.InstallsDetailByDistroAndVersion(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a time series of all the repository installs that match a
// particular criteria for a give time period. This is specific to a single repository.
//
// Default date range is 7 days ago. See response headers for [pagination](#pagination) information.
//
// Everyone for public repositories, Owners & Collaborators for private repositories.
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/stats/installs/series/weekly.json
// ```
func (c *Client) InstallsSeriesAll(
	ctx context.Context,
	request *packagecloud.StatsInstallsSeriesAllRequest,
	opts ...option.RequestOption,
) (*packagecloud.SeriesValue, error) {
	response, err := c.WithRawResponse.InstallsSeriesAll(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a time series of all the repository installs that match a
// particular criteria for a give time period. This is specific to a single repository.
//
// Default date range is 7 days ago. See response headers for [pagination](#pagination) information.
//
// Everyone for public repositories, Owners & Collaborators for private repositories.
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/stats/installs/series/weekly.json
// ```
func (c *Client) InstallsSeriesByDistro(
	ctx context.Context,
	request *packagecloud.StatsInstallsSeriesByDistroRequest,
	opts ...option.RequestOption,
) (*packagecloud.SeriesValue, error) {
	response, err := c.WithRawResponse.InstallsSeriesByDistro(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve a time series of all the repository installs that match a
// particular criteria for a give time period. This is specific to a single repository.
//
// Default date range is 7 days ago. See response headers for [pagination](#pagination) information.
//
// Everyone for public repositories, Owners & Collaborators for private repositories.
//
// **Example request:**
//
// ```
// /api/v1/repos/julio/test_repo/stats/installs/series/weekly.json
// ```
func (c *Client) InstallsSeriesByDistroAndVersion(
	ctx context.Context,
	request *packagecloud.StatsInstallsSeriesByDistroAndVersionRequest,
	opts ...option.RequestOption,
) (*packagecloud.SeriesValue, error) {
	response, err := c.WithRawResponse.InstallsSeriesByDistroAndVersion(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
