// Code generated by Fern. DO NOT EDIT.

package repositories

import (
	context "context"

	packagecloud "github.com/cstrahan/packagecloud-go/sdk"
	core "github.com/cstrahan/packagecloud-go/sdk/core"
	internal "github.com/cstrahan/packagecloud-go/sdk/internal"
	option "github.com/cstrahan/packagecloud-go/sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// **Example request:**
//
// ```
// curl https://packagecloud.io/api/v1/repos
// ```
func (c *Client) Index(
	ctx context.Context,
	request *packagecloud.RepositoriesIndexRequest,
	opts ...option.RequestOption,
) ([]*packagecloud.Repository, error) {
	response, err := c.WithRawResponse.Index(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// **Example request:**
//
// ```
//
//	curl -X POST                                                  \
//	     -H "Content-Type: application/json"                      \
//	     -d '{"repository": {"name": "thename", "private": "1"}}' \
//	     "https://packagecloud.io/api/v1/repos.json"
//
// ```
func (c *Client) Create(
	ctx context.Context,
	request *packagecloud.RepositoriesCreateRequest,
	opts ...option.RequestOption,
) (*packagecloud.RepositoryCreated, error) {
	response, err := c.WithRawResponse.Create(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// **Example request:**
//
// ```
// curl https://packagecloud.io/api/v1/repos/cooluser/myrepo
// ```
func (c *Client) Show(
	ctx context.Context,
	request *packagecloud.RepositoriesShowRequest,
	opts ...option.RequestOption,
) (*packagecloud.Repository, error) {
	response, err := c.WithRawResponse.Show(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// **Example request:**
//
// ```
// curl https://packagecloud.io/api/v1/repos/cooluser/myrepo/packages_with_bk_required_attributes
// ```
func (c *Client) PackagesWithBkRequiredAttributes(
	ctx context.Context,
	request *packagecloud.RepositoriesPackagesWithBkRequiredAttributesRequest,
	opts ...option.RequestOption,
) (map[string]any, error) {
	response, err := c.WithRawResponse.PackagesWithBkRequiredAttributes(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
