// Code generated by Fern. DO NOT EDIT.

package packages_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	strings "strings"
	testing "testing"

	packagecloud "github.com/cstrahan/packagecloud-go/sdk"
	client "github.com/cstrahan/packagecloud-go/sdk/client"
	option "github.com/cstrahan/packagecloud-go/sdk/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestPackagesContentsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesContentsRequest{
		UserID: "user_id",
		Repo:   "repo",
		PackagePackageFile: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.Packages.Contents(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesContentsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesContentsWithWireMock", "POST", "/api/v1/repos/user_id/repo/packages/contents.json", nil, 1)
}

func TestPackagesAllWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesAllRequest{
		UserID: "user_id",
		Repo:   "repo",
	}
	_, invocationErr := client.Packages.All(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesAllWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesAllWithWireMock", "GET", "/api/v1/repos/user_id/repo/packages.json", nil, 1)
}

func TestPackagesCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesCreateRequest{
		UserID: "user_id",
		Repo:   "repo",
		PackagePackageFile: strings.NewReader(
			"",
		),
	}
	_, invocationErr := client.Packages.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesCreateWithWireMock", "POST", "/api/v1/repos/user_id/repo/packages.json", nil, 1)
}

func TestPackagesPromoteWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesPromoteRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Distro:  "distro",
		Version: "version",
		Package: "package",
	}
	_, invocationErr := client.Packages.Promote(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesPromoteWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesPromoteWithWireMock", "POST", "/api/v1/repos/user_id/repo/distro/version/package/promote.json", nil, 1)
}

func TestPackagesShowWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesShowRequest{
		UserID:         "user_id",
		Repo:           "repo",
		Type:           "type",
		Distro:         "distro",
		Version:        "version",
		Package:        "package",
		Arch:           "arch",
		PackageVersion: "package_version",
		Release:        "release",
	}
	_, invocationErr := client.Packages.Show(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesShowWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesShowWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/type/distro/version/package/arch/package_version/release.json", nil, 1)
}

func TestPackagesAnyfileShowWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesAnyfileShowRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Package: "package",
		Version: "version",
	}
	_, invocationErr := client.Packages.AnyfileShow(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesAnyfileShowWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesAnyfileShowWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/anyfile/package/version.json", nil, 1)
}

func TestPackagesGemShowWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesGemShowRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Package: "package",
		Version: "version",
	}
	_, invocationErr := client.Packages.GemShow(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesGemShowWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesGemShowWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/gem/package/version.json", nil, 1)
}

func TestPackagesPythonShowWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesPythonShowRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Package: "package",
		Version: "version",
	}
	_, invocationErr := client.Packages.PythonShow(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesPythonShowWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesPythonShowWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/python/package/version.json", nil, 1)
}

func TestPackagesJavaShowWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesJavaShowRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Package: "package",
		Version: "version",
	}
	_, invocationErr := client.Packages.JavaShow(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesJavaShowWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesJavaShowWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/java/maven2/package/version.json", nil, 1)
}

func TestPackagesHelmShowWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesHelmShowRequest{
		UserID:    "user_id",
		Repo:      "repo",
		IndexName: "index_name",
		Package:   "package",
		Version:   "version",
	}
	_, invocationErr := client.Packages.HelmShow(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesHelmShowWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesHelmShowWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/helm/index_name/package/version.json", nil, 1)
}

func TestPackagesVersionsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesVersionsRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Type:    "type",
		Distro:  "distro",
		Version: "version",
		Package: "package",
		Arch:    "arch",
	}
	_, invocationErr := client.Packages.Versions(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesVersionsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesVersionsWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/type/distro/version/package/arch/versions.json", nil, 1)
}

func TestPackagesGemVersionsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesGemVersionsRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Package: "package",
	}
	_, invocationErr := client.Packages.GemVersions(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesGemVersionsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesGemVersionsWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/gem/package/versions.json", nil, 1)
}

func TestPackagesNodeShowWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesNodeShowRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Package: "package",
		Version: "version",
	}
	_, invocationErr := client.Packages.NodeShow(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesNodeShowWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesNodeShowWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/node/package/version.json", nil, 1)
}

func TestPackagesNodeVersionsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesNodeVersionsRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Package: "package",
	}
	_, invocationErr := client.Packages.NodeVersions(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesNodeVersionsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesNodeVersionsWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/node/package/versions.json", nil, 1)
}

func TestPackagesPythonVersionsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesPythonVersionsRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Package: "package",
	}
	_, invocationErr := client.Packages.PythonVersions(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesPythonVersionsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesPythonVersionsWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/python/package/versions.json", nil, 1)
}

func TestPackagesJavaVersionsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesJavaVersionsRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Group:   "group",
		Package: "package",
	}
	_, invocationErr := client.Packages.JavaVersions(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesJavaVersionsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesJavaVersionsWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/java/maven2/group/package/versions.json", nil, 1)
}

func TestPackagesAnyfileVersionsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesAnyfileVersionsRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Package: "package",
	}
	_, invocationErr := client.Packages.AnyfileVersions(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesAnyfileVersionsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesAnyfileVersionsWithWireMock", "GET", "/api/v1/repos/user_id/repo/package/anyfile/package/versions.json", nil, 1)
}

func TestPackagesIndexWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesIndexRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Type:    "type",
		Distro:  "distro",
		Version: "version",
		Arch:    "arch",
	}
	_, invocationErr := client.Packages.Index(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesIndexWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesIndexWithWireMock", "GET", "/api/v1/repos/user_id/repo/packages/type/distro/version/arch.json", nil, 1)
}

func TestPackagesDestroyGemWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesDestroyGemRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Package: "package",
	}
	_, invocationErr := client.Packages.DestroyGem(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesDestroyGemWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesDestroyGemWithWireMock", "DELETE", "/api/v1/repos/user_id/repo/gems/package.gem", nil, 1)
}

func TestPackagesDestroyJavaWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesDestroyJavaRequest{
		UserID:   "user_id",
		Repo:     "repo",
		Group:    "group",
		Filename: "filename",
	}
	_, invocationErr := client.Packages.DestroyJava(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesDestroyJavaWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesDestroyJavaWithWireMock", "DELETE", "/api/v1/repos/user_id/repo/java/maven2/group/filename", nil, 1)
}

func TestPackagesDestroyWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesDestroyRequest{
		UserID:  "user_id",
		Repo:    "repo",
		Distro:  "distro",
		Version: "version",
		Package: "package",
		Ext:     "ext",
	}
	_, invocationErr := client.Packages.Destroy(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesDestroyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesDestroyWithWireMock", "DELETE", "/api/v1/repos/user_id/repo/distro/version/package.ext", nil, 1)
}

func TestPackagesSearchWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.PackagesSearchRequest{
		UserID: "user_id",
		Repo:   "repo",
	}
	_, invocationErr := client.Packages.Search(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPackagesSearchWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPackagesSearchWithWireMock", "GET", "/api/v1/repos/user_id/repo/search.json", nil, 1)
}
