// Code generated by Fern. DO NOT EDIT.

package apitokens

import (
	context "context"

	packagecloud "github.com/cstrahan/packagecloud-go/sdk"
	core "github.com/cstrahan/packagecloud-go/sdk/core"
	internal "github.com/cstrahan/packagecloud-go/sdk/internal"
	option "github.com/cstrahan/packagecloud-go/sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Retrieve your API token programmatically. Authenticate with your packagecloud account email address (as the basic-auth username) and password (as the basic-auth password); be sure to URL-encode the username and password if you embed them in the URL.
//
// **Example request:**
//
// ```
// curl "https://hi%40hi.com:Asdd45VvaarT4591@packagecloud.io/api/v1/token.json"
// ```
func (c *Client) GetToken(
	ctx context.Context,
	opts ...option.RequestOption,
) (*packagecloud.APIToken, error) {
	response, err := c.WithRawResponse.GetToken(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
