// Code generated by Fern. DO NOT EDIT.

package read_tokens_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	packagecloud "github.com/cstrahan/packagecloud-go/sdk"
	client "github.com/cstrahan/packagecloud-go/sdk/client"
	option "github.com/cstrahan/packagecloud-go/sdk/option"
	require "github.com/stretchr/testify/require"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestReadTokensIndexWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.ReadTokensIndexRequest{
		UserID:      "user_id",
		Repo:        "repo",
		MasterToken: "master_token",
	}
	_, invocationErr := client.ReadTokens.Index(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReadTokensIndexWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReadTokensIndexWithWireMock", "GET", "/api/v1/repos/user_id/repo/master_tokens/master_token/read_tokens.json", nil, 1)
}

func TestReadTokensCreateWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.ReadTokensCreateRequest{
		UserID:      "user_id",
		Repo:        "repo",
		MasterToken: "master_token",
	}
	_, invocationErr := client.ReadTokens.Create(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReadTokensCreateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReadTokensCreateWithWireMock", "POST", "/api/v1/repos/user_id/repo/master_tokens/master_token/read_tokens.json", nil, 1)
}

func TestReadTokensShowWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.ReadTokensShowRequest{
		UserID:      "user_id",
		Repo:        "repo",
		MasterToken: "master_token",
		ID:          1,
	}
	_, invocationErr := client.ReadTokens.Show(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReadTokensShowWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReadTokensShowWithWireMock", "GET", "/api/v1/repos/user_id/repo/master_tokens/master_token/read_tokens/1", nil, 1)
}

func TestReadTokensDestroyWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &packagecloud.ReadTokensDestroyRequest{
		UserID:      "user_id",
		Repo:        "repo",
		MasterToken: "master_token",
		ID:          1,
	}
	invocationErr := client.ReadTokens.Destroy(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestReadTokensDestroyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestReadTokensDestroyWithWireMock", "DELETE", "/api/v1/repos/user_id/repo/master_tokens/master_token/read_tokens/1", nil, 1)
}
