// Code generated by Fern. DO NOT EDIT.

package distributions

import (
	context "context"

	packagecloud "github.com/cstrahan/packagecloud-go/sdk"
	core "github.com/cstrahan/packagecloud-go/sdk/core"
	internal "github.com/cstrahan/packagecloud-go/sdk/internal"
	option "github.com/cstrahan/packagecloud-go/sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// **Example request:**
//
// ```
// curl https://packagecloud.io/api/v1/distributions.json
// ```
func (c *Client) Index(
	ctx context.Context,
	opts ...option.RequestOption,
) (packagecloud.Distributions, error) {
	response, err := c.WithRawResponse.Index(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
