// Code generated by Fern. DO NOT EDIT.

package packagecloud

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/cstrahan/packagecloud-go/sdk/internal"
	big "math/big"
)

var (
	aPITokenFieldToken = big.NewInt(1 << 0)
)

type APIToken struct {
	// Your packagecloud API token, used for HTTP basic authentication on subsequent requests.
	Token *string `json:"token,omitempty" url:"token,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *APIToken) GetToken() *string {
	if a == nil {
		return nil
	}
	return a.Token
}

func (a *APIToken) GetExtraProperties() map[string]interface{} {
	if a == nil {
		return nil
	}
	return a.extraProperties
}

func (a *APIToken) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *APIToken) SetToken(token *string) {
	a.Token = token
	a.require(aPITokenFieldToken)
}

func (a *APIToken) UnmarshalJSON(data []byte) error {
	type unmarshaler APIToken
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = APIToken(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *APIToken) MarshalJSON() ([]byte, error) {
	type embed APIToken
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *APIToken) String() string {
	if a == nil {
		return "<nil>"
	}
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}
