// Code generated by Fern. DO NOT EDIT.

package packagecloud

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersGpgKeysCreateRequest(t *testing.T) {
	t.Run("SetUserID", func(t *testing.T) {
		obj := &GpgKeysCreateRequest{}
		var fernTestValueUserID string
		obj.SetUserID(fernTestValueUserID)
		assert.Equal(t, fernTestValueUserID, obj.UserID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRepo", func(t *testing.T) {
		obj := &GpgKeysCreateRequest{}
		var fernTestValueRepo string
		obj.SetRepo(fernTestValueRepo)
		assert.Equal(t, fernTestValueRepo, obj.Repo)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGpgKeysCreateRequest(t *testing.T) {
	t.Run("SetUserID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKeysCreateRequest{}
		var fernTestValueUserID string

		// Act
		obj.SetUserID(fernTestValueUserID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRepo_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKeysCreateRequest{}
		var fernTestValueRepo string

		// Act
		obj.SetRepo(fernTestValueRepo)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGpgKeysDestroyRequest(t *testing.T) {
	t.Run("SetUserID", func(t *testing.T) {
		obj := &GpgKeysDestroyRequest{}
		var fernTestValueUserID string
		obj.SetUserID(fernTestValueUserID)
		assert.Equal(t, fernTestValueUserID, obj.UserID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRepo", func(t *testing.T) {
		obj := &GpgKeysDestroyRequest{}
		var fernTestValueRepo string
		obj.SetRepo(fernTestValueRepo)
		assert.Equal(t, fernTestValueRepo, obj.Repo)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetKeyname", func(t *testing.T) {
		obj := &GpgKeysDestroyRequest{}
		var fernTestValueKeyname string
		obj.SetKeyname(fernTestValueKeyname)
		assert.Equal(t, fernTestValueKeyname, obj.Keyname)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGpgKeysDestroyRequest(t *testing.T) {
	t.Run("SetUserID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKeysDestroyRequest{}
		var fernTestValueUserID string

		// Act
		obj.SetUserID(fernTestValueUserID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRepo_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKeysDestroyRequest{}
		var fernTestValueRepo string

		// Act
		obj.SetRepo(fernTestValueRepo)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetKeyname_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKeysDestroyRequest{}
		var fernTestValueKeyname string

		// Act
		obj.SetKeyname(fernTestValueKeyname)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGpgKeysIndexRequest(t *testing.T) {
	t.Run("SetUserID", func(t *testing.T) {
		obj := &GpgKeysIndexRequest{}
		var fernTestValueUserID string
		obj.SetUserID(fernTestValueUserID)
		assert.Equal(t, fernTestValueUserID, obj.UserID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRepo", func(t *testing.T) {
		obj := &GpgKeysIndexRequest{}
		var fernTestValueRepo string
		obj.SetRepo(fernTestValueRepo)
		assert.Equal(t, fernTestValueRepo, obj.Repo)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGpgKeysIndexRequest(t *testing.T) {
	t.Run("SetUserID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKeysIndexRequest{}
		var fernTestValueUserID string

		// Act
		obj.SetUserID(fernTestValueUserID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRepo_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKeysIndexRequest{}
		var fernTestValueRepo string

		// Act
		obj.SetRepo(fernTestValueRepo)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGpgKeysShowRequest(t *testing.T) {
	t.Run("SetUserID", func(t *testing.T) {
		obj := &GpgKeysShowRequest{}
		var fernTestValueUserID string
		obj.SetUserID(fernTestValueUserID)
		assert.Equal(t, fernTestValueUserID, obj.UserID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRepo", func(t *testing.T) {
		obj := &GpgKeysShowRequest{}
		var fernTestValueRepo string
		obj.SetRepo(fernTestValueRepo)
		assert.Equal(t, fernTestValueRepo, obj.Repo)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetKeyname", func(t *testing.T) {
		obj := &GpgKeysShowRequest{}
		var fernTestValueKeyname string
		obj.SetKeyname(fernTestValueKeyname)
		assert.Equal(t, fernTestValueKeyname, obj.Keyname)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGpgKeysShowRequest(t *testing.T) {
	t.Run("SetUserID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKeysShowRequest{}
		var fernTestValueUserID string

		// Act
		obj.SetUserID(fernTestValueUserID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRepo_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKeysShowRequest{}
		var fernTestValueRepo string

		// Act
		obj.SetRepo(fernTestValueRepo)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetKeyname_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKeysShowRequest{}
		var fernTestValueKeyname string

		// Act
		obj.SetKeyname(fernTestValueKeyname)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGpgKey(t *testing.T) {
	t.Run("SetName", func(t *testing.T) {
		obj := &GpgKey{}
		var fernTestValueName *string
		obj.SetName(fernTestValueName)
		assert.Equal(t, fernTestValueName, obj.Name)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFingerprint", func(t *testing.T) {
		obj := &GpgKey{}
		var fernTestValueFingerprint *string
		obj.SetFingerprint(fernTestValueFingerprint)
		assert.Equal(t, fernTestValueFingerprint, obj.Fingerprint)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetKeytype", func(t *testing.T) {
		obj := &GpgKey{}
		var fernTestValueKeytype *string
		obj.SetKeytype(fernTestValueKeytype)
		assert.Equal(t, fernTestValueKeytype, obj.Keytype)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSelf", func(t *testing.T) {
		obj := &GpgKey{}
		var fernTestValueSelf *string
		obj.SetSelf(fernTestValueSelf)
		assert.Equal(t, fernTestValueSelf, obj.Self)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDestroyURL", func(t *testing.T) {
		obj := &GpgKey{}
		var fernTestValueDestroyURL *string
		obj.SetDestroyURL(fernTestValueDestroyURL)
		assert.Equal(t, fernTestValueDestroyURL, obj.DestroyURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDownloadURL", func(t *testing.T) {
		obj := &GpgKey{}
		var fernTestValueDownloadURL *string
		obj.SetDownloadURL(fernTestValueDownloadURL)
		assert.Equal(t, fernTestValueDownloadURL, obj.DownloadURL)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersGpgKey(t *testing.T) {
	t.Run("GetName", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		var expected *string
		obj.Name = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetName(), "getter should return the property value")
	})

	t.Run("GetName_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		obj.Name = nil

		// Act & Assert
		assert.Nil(t, obj.GetName(), "getter should return nil when property is nil")
	})

	t.Run("GetName_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GpgKey
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetName() // Should return zero value
	})

	t.Run("GetFingerprint", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		var expected *string
		obj.Fingerprint = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetFingerprint(), "getter should return the property value")
	})

	t.Run("GetFingerprint_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		obj.Fingerprint = nil

		// Act & Assert
		assert.Nil(t, obj.GetFingerprint(), "getter should return nil when property is nil")
	})

	t.Run("GetFingerprint_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GpgKey
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetFingerprint() // Should return zero value
	})

	t.Run("GetKeytype", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		var expected *string
		obj.Keytype = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetKeytype(), "getter should return the property value")
	})

	t.Run("GetKeytype_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		obj.Keytype = nil

		// Act & Assert
		assert.Nil(t, obj.GetKeytype(), "getter should return nil when property is nil")
	})

	t.Run("GetKeytype_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GpgKey
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetKeytype() // Should return zero value
	})

	t.Run("GetSelf", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		var expected *string
		obj.Self = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSelf(), "getter should return the property value")
	})

	t.Run("GetSelf_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		obj.Self = nil

		// Act & Assert
		assert.Nil(t, obj.GetSelf(), "getter should return nil when property is nil")
	})

	t.Run("GetSelf_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GpgKey
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSelf() // Should return zero value
	})

	t.Run("GetDestroyURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		var expected *string
		obj.DestroyURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDestroyURL(), "getter should return the property value")
	})

	t.Run("GetDestroyURL_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		obj.DestroyURL = nil

		// Act & Assert
		assert.Nil(t, obj.GetDestroyURL(), "getter should return nil when property is nil")
	})

	t.Run("GetDestroyURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GpgKey
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDestroyURL() // Should return zero value
	})

	t.Run("GetDownloadURL", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		var expected *string
		obj.DownloadURL = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetDownloadURL(), "getter should return the property value")
	})

	t.Run("GetDownloadURL_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		obj.DownloadURL = nil

		// Act & Assert
		assert.Nil(t, obj.GetDownloadURL(), "getter should return nil when property is nil")
	})

	t.Run("GetDownloadURL_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GpgKey
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetDownloadURL() // Should return zero value
	})

}

func TestSettersMarkExplicitGpgKey(t *testing.T) {
	t.Run("SetName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		var fernTestValueName *string

		// Act
		obj.SetName(fernTestValueName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFingerprint_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		var fernTestValueFingerprint *string

		// Act
		obj.SetFingerprint(fernTestValueFingerprint)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetKeytype_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		var fernTestValueKeytype *string

		// Act
		obj.SetKeytype(fernTestValueKeytype)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSelf_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		var fernTestValueSelf *string

		// Act
		obj.SetSelf(fernTestValueSelf)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDestroyURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		var fernTestValueDestroyURL *string

		// Act
		obj.SetDestroyURL(fernTestValueDestroyURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDownloadURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}
		var fernTestValueDownloadURL *string

		// Act
		obj.SetDownloadURL(fernTestValueDownloadURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGpgKeyList(t *testing.T) {
	t.Run("SetGpgKeys", func(t *testing.T) {
		obj := &GpgKeyList{}
		var fernTestValueGpgKeys []*GpgKey
		obj.SetGpgKeys(fernTestValueGpgKeys)
		assert.Equal(t, fernTestValueGpgKeys, obj.GpgKeys)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersGpgKeyList(t *testing.T) {
	t.Run("GetGpgKeys", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKeyList{}
		var expected []*GpgKey
		obj.GpgKeys = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetGpgKeys(), "getter should return the property value")
	})

	t.Run("GetGpgKeys_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKeyList{}
		obj.GpgKeys = nil

		// Act & Assert
		assert.Nil(t, obj.GetGpgKeys(), "getter should return nil when property is nil")
	})

	t.Run("GetGpgKeys_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GpgKeyList
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetGpgKeys() // Should return zero value
	})

}

func TestSettersMarkExplicitGpgKeyList(t *testing.T) {
	t.Run("SetGpgKeys_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKeyList{}
		var fernTestValueGpgKeys []*GpgKey

		// Act
		obj.SetGpgKeys(fernTestValueGpgKeys)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingGpgKey(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKey{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled GpgKey
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj GpgKey
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj GpgKey
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestJSONMarshalingGpgKeyList(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GpgKeyList{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled GpgKeyList
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj GpgKeyList
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj GpgKeyList
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringGpgKey(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &GpgKey{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GpgKey
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestStringGpgKeyList(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &GpgKeyList{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GpgKeyList
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesGpgKey(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &GpgKey{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GpgKey
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}

func TestExtraPropertiesGpgKeyList(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &GpgKeyList{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *GpgKeyList
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
