// Code generated by Fern. DO NOT EDIT.

package packagecloud

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/cstrahan/packagecloud-go/sdk/internal"
	io "io"
	big "math/big"
)

var (
	gpgKeysCreateRequestFieldUserID = big.NewInt(1 << 0)
	gpgKeysCreateRequestFieldRepo   = big.NewInt(1 << 1)
)

type GpgKeysCreateRequest struct {
	// The username to which the repo belongs.
	UserID string `json:"-" url:"-"`
	// The name of the repo.
	Repo          string    `json:"-" url:"-"`
	GpgKeyKeydata io.Reader `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GpgKeysCreateRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GpgKeysCreateRequest) SetUserID(userID string) {
	g.UserID = userID
	g.require(gpgKeysCreateRequestFieldUserID)
}

// SetRepo sets the Repo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GpgKeysCreateRequest) SetRepo(repo string) {
	g.Repo = repo
	g.require(gpgKeysCreateRequestFieldRepo)
}

func (g *GpgKeysCreateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GpgKeysCreateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GpgKeysCreateRequest(body)
	return nil
}

func (g *GpgKeysCreateRequest) MarshalJSON() ([]byte, error) {
	type embed GpgKeysCreateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	gpgKeysDestroyRequestFieldUserID  = big.NewInt(1 << 0)
	gpgKeysDestroyRequestFieldRepo    = big.NewInt(1 << 1)
	gpgKeysDestroyRequestFieldKeyname = big.NewInt(1 << 2)
)

type GpgKeysDestroyRequest struct {
	// The username to which the repo belongs.
	UserID string `json:"-" url:"-"`
	// The name of the repo.
	Repo string `json:"-" url:"-"`
	// The GPG Key keyname to delete
	Keyname string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GpgKeysDestroyRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GpgKeysDestroyRequest) SetUserID(userID string) {
	g.UserID = userID
	g.require(gpgKeysDestroyRequestFieldUserID)
}

// SetRepo sets the Repo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GpgKeysDestroyRequest) SetRepo(repo string) {
	g.Repo = repo
	g.require(gpgKeysDestroyRequestFieldRepo)
}

// SetKeyname sets the Keyname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GpgKeysDestroyRequest) SetKeyname(keyname string) {
	g.Keyname = keyname
	g.require(gpgKeysDestroyRequestFieldKeyname)
}

var (
	gpgKeysIndexRequestFieldUserID = big.NewInt(1 << 0)
	gpgKeysIndexRequestFieldRepo   = big.NewInt(1 << 1)
)

type GpgKeysIndexRequest struct {
	UserID string `json:"-" url:"-"`
	Repo   string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GpgKeysIndexRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GpgKeysIndexRequest) SetUserID(userID string) {
	g.UserID = userID
	g.require(gpgKeysIndexRequestFieldUserID)
}

// SetRepo sets the Repo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GpgKeysIndexRequest) SetRepo(repo string) {
	g.Repo = repo
	g.require(gpgKeysIndexRequestFieldRepo)
}

var (
	gpgKeysShowRequestFieldUserID  = big.NewInt(1 << 0)
	gpgKeysShowRequestFieldRepo    = big.NewInt(1 << 1)
	gpgKeysShowRequestFieldKeyname = big.NewInt(1 << 2)
)

type GpgKeysShowRequest struct {
	// The username to which the repo belongs.
	UserID string `json:"-" url:"-"`
	// The name of the repo.
	Repo string `json:"-" url:"-"`
	// The GPG Key keyname.
	Keyname string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GpgKeysShowRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GpgKeysShowRequest) SetUserID(userID string) {
	g.UserID = userID
	g.require(gpgKeysShowRequestFieldUserID)
}

// SetRepo sets the Repo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GpgKeysShowRequest) SetRepo(repo string) {
	g.Repo = repo
	g.require(gpgKeysShowRequestFieldRepo)
}

// SetKeyname sets the Keyname field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GpgKeysShowRequest) SetKeyname(keyname string) {
	g.Keyname = keyname
	g.require(gpgKeysShowRequestFieldKeyname)
}

var (
	gpgKeyFieldName        = big.NewInt(1 << 0)
	gpgKeyFieldFingerprint = big.NewInt(1 << 1)
	gpgKeyFieldKeytype     = big.NewInt(1 << 2)
	gpgKeyFieldSelf        = big.NewInt(1 << 3)
	gpgKeyFieldDestroyURL  = big.NewInt(1 << 4)
	gpgKeyFieldDownloadURL = big.NewInt(1 << 5)
)

type GpgKey struct {
	// The name of the GPG key.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// The GPG key's fingerprint.
	Fingerprint *string `json:"fingerprint,omitempty" url:"fingerprint,omitempty"`
	// The GPG key type ('repo' for repository signing keys or 'package' for package signing keys).
	Keytype *string `json:"keytype,omitempty" url:"keytype,omitempty"`
	// The URL for this object.
	Self *string `json:"self,omitempty" url:"self,omitempty"`
	// The URL that can be used to delete this GPG key.
	DestroyURL *string `json:"destroy_url,omitempty" url:"destroy_url,omitempty"`
	// The URL that can be used to download the GPG public key data.
	DownloadURL *string `json:"download_url,omitempty" url:"download_url,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GpgKey) GetName() *string {
	if g == nil {
		return nil
	}
	return g.Name
}

func (g *GpgKey) GetFingerprint() *string {
	if g == nil {
		return nil
	}
	return g.Fingerprint
}

func (g *GpgKey) GetKeytype() *string {
	if g == nil {
		return nil
	}
	return g.Keytype
}

func (g *GpgKey) GetSelf() *string {
	if g == nil {
		return nil
	}
	return g.Self
}

func (g *GpgKey) GetDestroyURL() *string {
	if g == nil {
		return nil
	}
	return g.DestroyURL
}

func (g *GpgKey) GetDownloadURL() *string {
	if g == nil {
		return nil
	}
	return g.DownloadURL
}

func (g *GpgKey) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GpgKey) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GpgKey) SetName(name *string) {
	g.Name = name
	g.require(gpgKeyFieldName)
}

// SetFingerprint sets the Fingerprint field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GpgKey) SetFingerprint(fingerprint *string) {
	g.Fingerprint = fingerprint
	g.require(gpgKeyFieldFingerprint)
}

// SetKeytype sets the Keytype field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GpgKey) SetKeytype(keytype *string) {
	g.Keytype = keytype
	g.require(gpgKeyFieldKeytype)
}

// SetSelf sets the Self field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GpgKey) SetSelf(self *string) {
	g.Self = self
	g.require(gpgKeyFieldSelf)
}

// SetDestroyURL sets the DestroyURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GpgKey) SetDestroyURL(destroyURL *string) {
	g.DestroyURL = destroyURL
	g.require(gpgKeyFieldDestroyURL)
}

// SetDownloadURL sets the DownloadURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GpgKey) SetDownloadURL(downloadURL *string) {
	g.DownloadURL = downloadURL
	g.require(gpgKeyFieldDownloadURL)
}

func (g *GpgKey) UnmarshalJSON(data []byte) error {
	type unmarshaler GpgKey
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GpgKey(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GpgKey) MarshalJSON() ([]byte, error) {
	type embed GpgKey
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GpgKey) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	gpgKeysIndexResponseFieldGpgKeys = big.NewInt(1 << 0)
)

type GpgKeysIndexResponse struct {
	GpgKeys []*GpgKey `json:"gpg_keys" url:"gpg_keys"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GpgKeysIndexResponse) GetGpgKeys() []*GpgKey {
	if g == nil {
		return nil
	}
	return g.GpgKeys
}

func (g *GpgKeysIndexResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GpgKeysIndexResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetGpgKeys sets the GpgKeys field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GpgKeysIndexResponse) SetGpgKeys(gpgKeys []*GpgKey) {
	g.GpgKeys = gpgKeys
	g.require(gpgKeysIndexResponseFieldGpgKeys)
}

func (g *GpgKeysIndexResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GpgKeysIndexResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GpgKeysIndexResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GpgKeysIndexResponse) MarshalJSON() ([]byte, error) {
	type embed GpgKeysIndexResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GpgKeysIndexResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}
