// Code generated by Fern. DO NOT EDIT.

package packagecloud

import (
	json "encoding/json"
	internal "github.com/cstrahan/packagecloud-go/sdk/internal"
	big "math/big"
)

var (
	installConfigFileListRequestFieldUserID = big.NewInt(1 << 0)
	installConfigFileListRequestFieldRepo   = big.NewInt(1 << 1)
	installConfigFileListRequestFieldDist   = big.NewInt(1 << 2)
	installConfigFileListRequestFieldName   = big.NewInt(1 << 3)
	installConfigFileListRequestFieldOs     = big.NewInt(1 << 4)
)

type InstallConfigFileListRequest struct {
	// The username the repository belongs to.
	UserID string `json:"-" url:"-"`
	// The name of the repository.
	Repo string `json:"-" url:"-"`
	// Distribution version, e.g. `precise`, `8`, `13.2`.
	Dist string `json:"-" url:"dist"`
	// A unique identifier for the consuming system; a read token created/reused under this name is embedded in the output.
	Name string `json:"-" url:"name"`
	// Target distribution, e.g. `ubuntu`, `el`, `opensuse`.
	Os string `json:"-" url:"os"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InstallConfigFileListRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallConfigFileListRequest) SetUserID(userID string) {
	i.UserID = userID
	i.require(installConfigFileListRequestFieldUserID)
}

// SetRepo sets the Repo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallConfigFileListRequest) SetRepo(repo string) {
	i.Repo = repo
	i.require(installConfigFileListRequestFieldRepo)
}

// SetDist sets the Dist field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallConfigFileListRequest) SetDist(dist string) {
	i.Dist = dist
	i.require(installConfigFileListRequestFieldDist)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallConfigFileListRequest) SetName(name string) {
	i.Name = name
	i.require(installConfigFileListRequestFieldName)
}

// SetOs sets the Os field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallConfigFileListRequest) SetOs(os string) {
	i.Os = os
	i.require(installConfigFileListRequestFieldOs)
}

var (
	installConfigFileRepoRequestFieldUserID = big.NewInt(1 << 0)
	installConfigFileRepoRequestFieldRepo   = big.NewInt(1 << 1)
	installConfigFileRepoRequestFieldDist   = big.NewInt(1 << 2)
	installConfigFileRepoRequestFieldName   = big.NewInt(1 << 3)
	installConfigFileRepoRequestFieldOs     = big.NewInt(1 << 4)
)

type InstallConfigFileRepoRequest struct {
	// The username the repository belongs to.
	UserID string `json:"-" url:"-"`
	// The name of the repository.
	Repo string `json:"-" url:"-"`
	// Distribution version, e.g. `precise`, `8`, `13.2`.
	Dist string `json:"-" url:"dist"`
	// A unique identifier for the consuming system; a read token created/reused under this name is embedded in the output.
	Name string `json:"-" url:"name"`
	// Target distribution, e.g. `ubuntu`, `el`, `opensuse`.
	Os string `json:"-" url:"os"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InstallConfigFileRepoRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallConfigFileRepoRequest) SetUserID(userID string) {
	i.UserID = userID
	i.require(installConfigFileRepoRequestFieldUserID)
}

// SetRepo sets the Repo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallConfigFileRepoRequest) SetRepo(repo string) {
	i.Repo = repo
	i.require(installConfigFileRepoRequestFieldRepo)
}

// SetDist sets the Dist field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallConfigFileRepoRequest) SetDist(dist string) {
	i.Dist = dist
	i.require(installConfigFileRepoRequestFieldDist)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallConfigFileRepoRequest) SetName(name string) {
	i.Name = name
	i.require(installConfigFileRepoRequestFieldName)
}

// SetOs sets the Os field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallConfigFileRepoRequest) SetOs(os string) {
	i.Os = os
	i.require(installConfigFileRepoRequestFieldOs)
}

var (
	installGpgKeyURLRequestFieldUserID = big.NewInt(1 << 0)
	installGpgKeyURLRequestFieldRepo   = big.NewInt(1 << 1)
	installGpgKeyURLRequestFieldDist   = big.NewInt(1 << 2)
	installGpgKeyURLRequestFieldName   = big.NewInt(1 << 3)
	installGpgKeyURLRequestFieldOs     = big.NewInt(1 << 4)
)

type InstallGpgKeyURLRequest struct {
	// The username the repository belongs to.
	UserID string `json:"-" url:"-"`
	// The name of the repository.
	Repo string `json:"-" url:"-"`
	// Distribution version, e.g. `precise`, `8`, `13.2`.
	Dist string `json:"-" url:"dist"`
	// A unique identifier for the consuming system; a read token created/reused under this name is embedded in the output.
	Name string `json:"-" url:"name"`
	// Target distribution, e.g. `ubuntu`, `el`, `opensuse`.
	Os string `json:"-" url:"os"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InstallGpgKeyURLRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallGpgKeyURLRequest) SetUserID(userID string) {
	i.UserID = userID
	i.require(installGpgKeyURLRequestFieldUserID)
}

// SetRepo sets the Repo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallGpgKeyURLRequest) SetRepo(repo string) {
	i.Repo = repo
	i.require(installGpgKeyURLRequestFieldRepo)
}

// SetDist sets the Dist field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallGpgKeyURLRequest) SetDist(dist string) {
	i.Dist = dist
	i.require(installGpgKeyURLRequestFieldDist)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallGpgKeyURLRequest) SetName(name string) {
	i.Name = name
	i.require(installGpgKeyURLRequestFieldName)
}

// SetOs sets the Os field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallGpgKeyURLRequest) SetOs(os string) {
	i.Os = os
	i.require(installGpgKeyURLRequestFieldOs)
}

var (
	installTokenRequestFieldUserID = big.NewInt(1 << 0)
	installTokenRequestFieldRepo   = big.NewInt(1 << 1)
	installTokenRequestFieldName   = big.NewInt(1 << 2)
)

type InstallTokenRequest struct {
	// The username the repository belongs to.
	UserID string `json:"-" url:"-"`
	// The name of the repository.
	Repo string `json:"-" url:"-"`
	// Unique identifier; the read token is created/reused under this name.
	Name string `json:"name" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *InstallTokenRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallTokenRequest) SetUserID(userID string) {
	i.UserID = userID
	i.require(installTokenRequestFieldUserID)
}

// SetRepo sets the Repo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallTokenRequest) SetRepo(repo string) {
	i.Repo = repo
	i.require(installTokenRequestFieldRepo)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *InstallTokenRequest) SetName(name string) {
	i.Name = name
	i.require(installTokenRequestFieldName)
}

func (i *InstallTokenRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler InstallTokenRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*i = InstallTokenRequest(body)
	return nil
}

func (i *InstallTokenRequest) MarshalJSON() ([]byte, error) {
	type embed InstallTokenRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}
