// Code generated by Fern. DO NOT EDIT.

package packagecloud

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersLicensesIndexRequest(t *testing.T) {
	t.Run("SetLicenseKey", func(t *testing.T) {
		obj := &LicensesIndexRequest{}
		var fernTestValueLicenseKey string
		obj.SetLicenseKey(fernTestValueLicenseKey)
		assert.Equal(t, fernTestValueLicenseKey, obj.LicenseKey)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitLicensesIndexRequest(t *testing.T) {
	t.Run("SetLicenseKey_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &LicensesIndexRequest{}
		var fernTestValueLicenseKey string

		// Act
		obj.SetLicenseKey(fernTestValueLicenseKey)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersLicense(t *testing.T) {
	t.Run("SetLicense", func(t *testing.T) {
		obj := &License{}
		var fernTestValueLicense *string
		obj.SetLicense(fernTestValueLicense)
		assert.Equal(t, fernTestValueLicense, obj.License)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSignature", func(t *testing.T) {
		obj := &License{}
		var fernTestValueSignature *string
		obj.SetSignature(fernTestValueSignature)
		assert.Equal(t, fernTestValueSignature, obj.Signature)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersLicense(t *testing.T) {
	t.Run("GetLicense", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &License{}
		var expected *string
		obj.License = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetLicense(), "getter should return the property value")
	})

	t.Run("GetLicense_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &License{}
		obj.License = nil

		// Act & Assert
		assert.Nil(t, obj.GetLicense(), "getter should return nil when property is nil")
	})

	t.Run("GetLicense_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *License
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetLicense() // Should return zero value
	})

	t.Run("GetSignature", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &License{}
		var expected *string
		obj.Signature = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSignature(), "getter should return the property value")
	})

	t.Run("GetSignature_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &License{}
		obj.Signature = nil

		// Act & Assert
		assert.Nil(t, obj.GetSignature(), "getter should return nil when property is nil")
	})

	t.Run("GetSignature_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *License
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSignature() // Should return zero value
	})

}

func TestSettersMarkExplicitLicense(t *testing.T) {
	t.Run("SetLicense_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &License{}
		var fernTestValueLicense *string

		// Act
		obj.SetLicense(fernTestValueLicense)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSignature_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &License{}
		var fernTestValueSignature *string

		// Act
		obj.SetSignature(fernTestValueSignature)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingLicense(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &License{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled License
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj License
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj License
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringLicense(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &License{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *License
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestExtraPropertiesLicense(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &License{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *License
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
