// Code generated by Fern. DO NOT EDIT.

package packagecloud

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/cstrahan/packagecloud-go/sdk/internal"
	big "math/big"
)

var (
	masterTokensCreateRequestFieldUserID          = big.NewInt(1 << 0)
	masterTokensCreateRequestFieldRepo            = big.NewInt(1 << 1)
	masterTokensCreateRequestFieldMasterTokenName = big.NewInt(1 << 2)
)

type MasterTokensCreateRequest struct {
	// The username to which the repo belongs.
	UserID string `json:"-" url:"-"`
	// The name of the repo.
	Repo string `json:"-" url:"-"`
	// The name of the token to create.
	MasterTokenName *string `json:"master_token[name],omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MasterTokensCreateRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensCreateRequest) SetUserID(userID string) {
	m.UserID = userID
	m.require(masterTokensCreateRequestFieldUserID)
}

// SetRepo sets the Repo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensCreateRequest) SetRepo(repo string) {
	m.Repo = repo
	m.require(masterTokensCreateRequestFieldRepo)
}

// SetMasterTokenName sets the MasterTokenName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensCreateRequest) SetMasterTokenName(masterTokenName *string) {
	m.MasterTokenName = masterTokenName
	m.require(masterTokensCreateRequestFieldMasterTokenName)
}

func (m *MasterTokensCreateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler MasterTokensCreateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*m = MasterTokensCreateRequest(body)
	return nil
}

func (m *MasterTokensCreateRequest) MarshalJSON() ([]byte, error) {
	type embed MasterTokensCreateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	masterTokensDestroyRequestFieldUserID = big.NewInt(1 << 0)
	masterTokensDestroyRequestFieldRepo   = big.NewInt(1 << 1)
	masterTokensDestroyRequestFieldID     = big.NewInt(1 << 2)
)

type MasterTokensDestroyRequest struct {
	// The username to which the repo belongs.
	UserID string `json:"-" url:"-"`
	// The name of the repo.
	Repo string `json:"-" url:"-"`
	// The id of the master token to be destroyed.
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MasterTokensDestroyRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensDestroyRequest) SetUserID(userID string) {
	m.UserID = userID
	m.require(masterTokensDestroyRequestFieldUserID)
}

// SetRepo sets the Repo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensDestroyRequest) SetRepo(repo string) {
	m.Repo = repo
	m.require(masterTokensDestroyRequestFieldRepo)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensDestroyRequest) SetID(id int) {
	m.ID = id
	m.require(masterTokensDestroyRequestFieldID)
}

var (
	masterTokensIndexRequestFieldUserID = big.NewInt(1 << 0)
	masterTokensIndexRequestFieldRepo   = big.NewInt(1 << 1)
)

type MasterTokensIndexRequest struct {
	// The username to which the repo belongs.
	UserID string `json:"-" url:"-"`
	// The name of the repo.
	Repo string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MasterTokensIndexRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensIndexRequest) SetUserID(userID string) {
	m.UserID = userID
	m.require(masterTokensIndexRequestFieldUserID)
}

// SetRepo sets the Repo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensIndexRequest) SetRepo(repo string) {
	m.Repo = repo
	m.require(masterTokensIndexRequestFieldRepo)
}

var (
	masterTokensSearchRequestFieldUserID  = big.NewInt(1 << 0)
	masterTokensSearchRequestFieldRepo    = big.NewInt(1 << 1)
	masterTokensSearchRequestFieldPage    = big.NewInt(1 << 2)
	masterTokensSearchRequestFieldPerPage = big.NewInt(1 << 3)
	masterTokensSearchRequestFieldQ       = big.NewInt(1 << 4)
)

type MasterTokensSearchRequest struct {
	// The username to which the repo belongs.
	UserID string `json:"-" url:"-"`
	// The name of the repo.
	Repo string `json:"-" url:"-"`
	// One-based page index.
	Page *int `json:"-" url:"page,omitempty"`
	// Items per page (default 30). Values above the server's Max-Per-Page are clamped; inspect the Max-Per-Page response header for the effective cap.
	PerPage *int `json:"-" url:"per_page,omitempty"`
	// The name of the MasterToken.
	Q *string `json:"-" url:"q,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MasterTokensSearchRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensSearchRequest) SetUserID(userID string) {
	m.UserID = userID
	m.require(masterTokensSearchRequestFieldUserID)
}

// SetRepo sets the Repo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensSearchRequest) SetRepo(repo string) {
	m.Repo = repo
	m.require(masterTokensSearchRequestFieldRepo)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensSearchRequest) SetPage(page *int) {
	m.Page = page
	m.require(masterTokensSearchRequestFieldPage)
}

// SetPerPage sets the PerPage field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensSearchRequest) SetPerPage(perPage *int) {
	m.PerPage = perPage
	m.require(masterTokensSearchRequestFieldPerPage)
}

// SetQ sets the Q field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensSearchRequest) SetQ(q *string) {
	m.Q = q
	m.require(masterTokensSearchRequestFieldQ)
}

var (
	masterTokensShowRequestFieldUserID = big.NewInt(1 << 0)
	masterTokensShowRequestFieldRepo   = big.NewInt(1 << 1)
	masterTokensShowRequestFieldID     = big.NewInt(1 << 2)
)

type MasterTokensShowRequest struct {
	// The username to which the repo belongs.
	UserID string `json:"-" url:"-"`
	// The name of the repo.
	Repo string `json:"-" url:"-"`
	// The id or value of the MasterToken.
	ID int `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MasterTokensShowRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetUserID sets the UserID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensShowRequest) SetUserID(userID string) {
	m.UserID = userID
	m.require(masterTokensShowRequestFieldUserID)
}

// SetRepo sets the Repo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensShowRequest) SetRepo(repo string) {
	m.Repo = repo
	m.require(masterTokensShowRequestFieldRepo)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensShowRequest) SetID(id int) {
	m.ID = id
	m.require(masterTokensShowRequestFieldID)
}

var (
	masterTokenFieldName       = big.NewInt(1 << 0)
	masterTokenFieldValue      = big.NewInt(1 << 1)
	masterTokenFieldReadTokens = big.NewInt(1 << 2)
	masterTokenFieldPaths      = big.NewInt(1 << 3)
)

type MasterToken struct {
	// The name of the master token.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// The value of the master token, for use in the read token API.
	Value *string `json:"value,omitempty" url:"value,omitempty"`
	// An array of {ReadToken} objects that belong to this master token.
	ReadTokens []*MasterTokenReadTokensItem `json:"read_tokens,omitempty" url:"read_tokens,omitempty"`
	Paths      *MasterTokenPaths            `json:"paths,omitempty" url:"paths,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MasterToken) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MasterToken) GetValue() *string {
	if m == nil {
		return nil
	}
	return m.Value
}

func (m *MasterToken) GetReadTokens() []*MasterTokenReadTokensItem {
	if m == nil {
		return nil
	}
	return m.ReadTokens
}

func (m *MasterToken) GetPaths() *MasterTokenPaths {
	if m == nil {
		return nil
	}
	return m.Paths
}

func (m *MasterToken) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MasterToken) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterToken) SetName(name *string) {
	m.Name = name
	m.require(masterTokenFieldName)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterToken) SetValue(value *string) {
	m.Value = value
	m.require(masterTokenFieldValue)
}

// SetReadTokens sets the ReadTokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterToken) SetReadTokens(readTokens []*MasterTokenReadTokensItem) {
	m.ReadTokens = readTokens
	m.require(masterTokenFieldReadTokens)
}

// SetPaths sets the Paths field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterToken) SetPaths(paths *MasterTokenPaths) {
	m.Paths = paths
	m.require(masterTokenFieldPaths)
}

func (m *MasterToken) UnmarshalJSON(data []byte) error {
	type unmarshaler MasterToken
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MasterToken(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MasterToken) MarshalJSON() ([]byte, error) {
	type embed MasterToken
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MasterToken) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	masterTokenPathsFieldSelf = big.NewInt(1 << 0)
)

type MasterTokenPaths struct {
	// A URI for this master token. Can be used to destroy one.
	Self *string `json:"self,omitempty" url:"self,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MasterTokenPaths) GetSelf() *string {
	if m == nil {
		return nil
	}
	return m.Self
}

func (m *MasterTokenPaths) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MasterTokenPaths) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetSelf sets the Self field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokenPaths) SetSelf(self *string) {
	m.Self = self
	m.require(masterTokenPathsFieldSelf)
}

func (m *MasterTokenPaths) UnmarshalJSON(data []byte) error {
	type unmarshaler MasterTokenPaths
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MasterTokenPaths(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MasterTokenPaths) MarshalJSON() ([]byte, error) {
	type embed MasterTokenPaths
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MasterTokenPaths) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	masterTokenReadTokensItemFieldValue = big.NewInt(1 << 0)
	masterTokenReadTokensItemFieldName  = big.NewInt(1 << 1)
)

type MasterTokenReadTokensItem struct {
	Value *string `json:"value,omitempty" url:"value,omitempty"`
	Name  *string `json:"name,omitempty" url:"name,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MasterTokenReadTokensItem) GetValue() *string {
	if m == nil {
		return nil
	}
	return m.Value
}

func (m *MasterTokenReadTokensItem) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MasterTokenReadTokensItem) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MasterTokenReadTokensItem) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokenReadTokensItem) SetValue(value *string) {
	m.Value = value
	m.require(masterTokenReadTokensItemFieldValue)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokenReadTokensItem) SetName(name *string) {
	m.Name = name
	m.require(masterTokenReadTokensItemFieldName)
}

func (m *MasterTokenReadTokensItem) UnmarshalJSON(data []byte) error {
	type unmarshaler MasterTokenReadTokensItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MasterTokenReadTokensItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MasterTokenReadTokensItem) MarshalJSON() ([]byte, error) {
	type embed MasterTokenReadTokensItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MasterTokenReadTokensItem) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	masterTokensResultFieldName          = big.NewInt(1 << 0)
	masterTokensResultFieldValue         = big.NewInt(1 << 1)
	masterTokensResultFieldSelfURL       = big.NewInt(1 << 2)
	masterTokensResultFieldReadTokensURL = big.NewInt(1 << 3)
)

type MasterTokensResult struct {
	// The name of the master token.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// The value of the master token, for use in the read token API.
	Value *string `json:"value,omitempty" url:"value,omitempty"`
	// A URI for this master token. Can be used to destroy one.
	SelfURL *string `json:"self_url,omitempty" url:"self_url,omitempty"`
	// a URI to get all of the read tokens for this master token.
	ReadTokensURL *string `json:"read_tokens_url,omitempty" url:"read_tokens_url,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MasterTokensResult) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MasterTokensResult) GetValue() *string {
	if m == nil {
		return nil
	}
	return m.Value
}

func (m *MasterTokensResult) GetSelfURL() *string {
	if m == nil {
		return nil
	}
	return m.SelfURL
}

func (m *MasterTokensResult) GetReadTokensURL() *string {
	if m == nil {
		return nil
	}
	return m.ReadTokensURL
}

func (m *MasterTokensResult) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MasterTokensResult) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensResult) SetName(name *string) {
	m.Name = name
	m.require(masterTokensResultFieldName)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensResult) SetValue(value *string) {
	m.Value = value
	m.require(masterTokensResultFieldValue)
}

// SetSelfURL sets the SelfURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensResult) SetSelfURL(selfURL *string) {
	m.SelfURL = selfURL
	m.require(masterTokensResultFieldSelfURL)
}

// SetReadTokensURL sets the ReadTokensURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensResult) SetReadTokensURL(readTokensURL *string) {
	m.ReadTokensURL = readTokensURL
	m.require(masterTokensResultFieldReadTokensURL)
}

func (m *MasterTokensResult) UnmarshalJSON(data []byte) error {
	type unmarshaler MasterTokensResult
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MasterTokensResult(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MasterTokensResult) MarshalJSON() ([]byte, error) {
	type embed MasterTokensResult
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MasterTokensResult) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	masterTokensShowResponseItemFieldValue         = big.NewInt(1 << 0)
	masterTokensShowResponseItemFieldName          = big.NewInt(1 << 1)
	masterTokensShowResponseItemFieldReadTokensURL = big.NewInt(1 << 2)
)

type MasterTokensShowResponseItem struct {
	Value         *string `json:"value,omitempty" url:"value,omitempty"`
	Name          *string `json:"name,omitempty" url:"name,omitempty"`
	ReadTokensURL *string `json:"read_tokens_url,omitempty" url:"read_tokens_url,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MasterTokensShowResponseItem) GetValue() *string {
	if m == nil {
		return nil
	}
	return m.Value
}

func (m *MasterTokensShowResponseItem) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MasterTokensShowResponseItem) GetReadTokensURL() *string {
	if m == nil {
		return nil
	}
	return m.ReadTokensURL
}

func (m *MasterTokensShowResponseItem) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MasterTokensShowResponseItem) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensShowResponseItem) SetValue(value *string) {
	m.Value = value
	m.require(masterTokensShowResponseItemFieldValue)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensShowResponseItem) SetName(name *string) {
	m.Name = name
	m.require(masterTokensShowResponseItemFieldName)
}

// SetReadTokensURL sets the ReadTokensURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokensShowResponseItem) SetReadTokensURL(readTokensURL *string) {
	m.ReadTokensURL = readTokensURL
	m.require(masterTokensShowResponseItemFieldReadTokensURL)
}

func (m *MasterTokensShowResponseItem) UnmarshalJSON(data []byte) error {
	type unmarshaler MasterTokensShowResponseItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MasterTokensShowResponseItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MasterTokensShowResponseItem) MarshalJSON() ([]byte, error) {
	type embed MasterTokensShowResponseItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MasterTokensShowResponseItem) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}
