// Code generated by Fern. DO NOT EDIT.

package packagecloud

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/cstrahan/packagecloud-go/sdk/internal"
	big "math/big"
)

var (
	masterTokenReadTokensFieldName          = big.NewInt(1 << 0)
	masterTokenReadTokensFieldValue         = big.NewInt(1 << 1)
	masterTokenReadTokensFieldReadTokensURL = big.NewInt(1 << 2)
	masterTokenReadTokensFieldPaths         = big.NewInt(1 << 3)
)

type MasterTokenReadTokens struct {
	// The name of the master token.
	Name *string `json:"name,omitempty" url:"name,omitempty"`
	// The value of the master token, for use in the read token API.
	Value *string `json:"value,omitempty" url:"value,omitempty"`
	// a URI to get all of the read tokens for this master token.
	ReadTokensURL *string                     `json:"read_tokens_url,omitempty" url:"read_tokens_url,omitempty"`
	Paths         *MasterTokenReadTokensPaths `json:"paths,omitempty" url:"paths,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MasterTokenReadTokens) GetName() *string {
	if m == nil {
		return nil
	}
	return m.Name
}

func (m *MasterTokenReadTokens) GetValue() *string {
	if m == nil {
		return nil
	}
	return m.Value
}

func (m *MasterTokenReadTokens) GetReadTokensURL() *string {
	if m == nil {
		return nil
	}
	return m.ReadTokensURL
}

func (m *MasterTokenReadTokens) GetPaths() *MasterTokenReadTokensPaths {
	if m == nil {
		return nil
	}
	return m.Paths
}

func (m *MasterTokenReadTokens) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MasterTokenReadTokens) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokenReadTokens) SetName(name *string) {
	m.Name = name
	m.require(masterTokenReadTokensFieldName)
}

// SetValue sets the Value field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokenReadTokens) SetValue(value *string) {
	m.Value = value
	m.require(masterTokenReadTokensFieldValue)
}

// SetReadTokensURL sets the ReadTokensURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokenReadTokens) SetReadTokensURL(readTokensURL *string) {
	m.ReadTokensURL = readTokensURL
	m.require(masterTokenReadTokensFieldReadTokensURL)
}

// SetPaths sets the Paths field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokenReadTokens) SetPaths(paths *MasterTokenReadTokensPaths) {
	m.Paths = paths
	m.require(masterTokenReadTokensFieldPaths)
}

func (m *MasterTokenReadTokens) UnmarshalJSON(data []byte) error {
	type unmarshaler MasterTokenReadTokens
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MasterTokenReadTokens(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MasterTokenReadTokens) MarshalJSON() ([]byte, error) {
	type embed MasterTokenReadTokens
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MasterTokenReadTokens) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

var (
	masterTokenReadTokensPathsFieldSelf = big.NewInt(1 << 0)
)

type MasterTokenReadTokensPaths struct {
	// A URI for this master tokens read tokens.
	Self *string `json:"self,omitempty" url:"self,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (m *MasterTokenReadTokensPaths) GetSelf() *string {
	if m == nil {
		return nil
	}
	return m.Self
}

func (m *MasterTokenReadTokensPaths) GetExtraProperties() map[string]interface{} {
	if m == nil {
		return nil
	}
	return m.extraProperties
}

func (m *MasterTokenReadTokensPaths) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetSelf sets the Self field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MasterTokenReadTokensPaths) SetSelf(self *string) {
	m.Self = self
	m.require(masterTokenReadTokensPathsFieldSelf)
}

func (m *MasterTokenReadTokensPaths) UnmarshalJSON(data []byte) error {
	type unmarshaler MasterTokenReadTokensPaths
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*m = MasterTokenReadTokensPaths(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *m)
	if err != nil {
		return err
	}
	m.extraProperties = extraProperties
	m.rawJSON = json.RawMessage(data)
	return nil
}

func (m *MasterTokenReadTokensPaths) MarshalJSON() ([]byte, error) {
	type embed MasterTokenReadTokensPaths
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (m *MasterTokenReadTokensPaths) String() string {
	if m == nil {
		return "<nil>"
	}
	if len(m.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(m.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}
