// Code generated by Fern. DO NOT EDIT.

package client

import (
	apitokens "github.com/cstrahan/packagecloud-go/sdk/apitokens"
	core "github.com/cstrahan/packagecloud-go/sdk/core"
	distributions "github.com/cstrahan/packagecloud-go/sdk/distributions"
	gpgkeys "github.com/cstrahan/packagecloud-go/sdk/gpgkeys"
	install "github.com/cstrahan/packagecloud-go/sdk/install"
	internal "github.com/cstrahan/packagecloud-go/sdk/internal"
	licenses "github.com/cstrahan/packagecloud-go/sdk/licenses"
	mastertokens "github.com/cstrahan/packagecloud-go/sdk/mastertokens"
	option "github.com/cstrahan/packagecloud-go/sdk/option"
	packages "github.com/cstrahan/packagecloud-go/sdk/packages"
	readtokens "github.com/cstrahan/packagecloud-go/sdk/readtokens"
	repositories "github.com/cstrahan/packagecloud-go/sdk/repositories"
	stats "github.com/cstrahan/packagecloud-go/sdk/stats"
)

type Client struct {
	Distributions *distributions.Client
	GpgKeys       *gpgkeys.Client
	Licenses      *licenses.Client
	MasterTokens  *mastertokens.Client
	Packages      *packages.Client
	ReadTokens    *readtokens.Client
	Repositories  *repositories.Client
	Stats         *stats.Client
	APITokens     *apitokens.Client
	Install       *install.Client

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		Distributions: distributions.NewClient(options),
		GpgKeys:       gpgkeys.NewClient(options),
		Licenses:      licenses.NewClient(options),
		MasterTokens:  mastertokens.NewClient(options),
		Packages:      packages.NewClient(options),
		ReadTokens:    readtokens.NewClient(options),
		Repositories:  repositories.NewClient(options),
		Stats:         stats.NewClient(options),
		APITokens:     apitokens.NewClient(options),
		Install:       install.NewClient(options),
		options:       options,
		baseURL:       options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}
